import { Item } from "./views/Home/components/@types/Item";

export const items: Item[][] = [
    [
        {
            id: 1,
            name: "Cyberpunk 2077 Standard Edition - PS4, PS5",
            image: "https://source.unsplash.com/random",
            currency: "GHS",
            price: "30.99",
            discount: 0,
            tags: ["Action", "PS4"],
            description: "Cyberpunk 2077 is an open-world, action-adventure story set in Night City, a megalopolis obsessed with power, glamour and body modification. You play as V, a mercenary outlaw going after a one-of-a-kind implant that is the key to immortality.",
        },
        {
            id: 2,
            name: "Call Of Duty: Black Ops Cold War",
            image: "https://source.unsplash.com/random",
            currency: "GHS",
            price: "35.99",
            discount: 20,
            tags: ["Action", "PS5"],
            description: "Cyberpunk 2077 is an open-world, action-adventure story set in Night City, a megalopolis obsessed with power, glamour and body modification. You play as V, a mercenary outlaw going after a one-of-a-kind implant that is the key to immortality.",
        },
        {
            id: 3,
            name: "NBA 2K21 Mamba Forever - PlayStation 4",
            image: "https://source.unsplash.com/random",
            currency: "GHS",
            price: "40.49",
            discount: 0,
            tags: ["Action", "PS4"],
            description: "Cyberpunk 2077 is an open-world, action-adventure story set in Night City, a megalopolis obsessed with power, glamour and body modification. You play as V, a mercenary outlaw going after a one-of-a-kind implant that is the key to immortality.",
        },
        {
            id: 4,
            name: "Assasins Creed Valhalla",
            image: "https://source.unsplash.com/random",
            currency: "GHS",
            price: "30.99",
            discount: 0,
            tags: ["Action", "PS4"],
            description: "Cyberpunk 2077 is an open-world, action-adventure story set in Night City, a megalopolis obsessed with power, glamour and body modification. You play as V, a mercenary outlaw going after a one-of-a-kind implant that is the key to immortality.",
        },
        {
            id: 5,
            name: "Cyberpunk 2077 Standard Edition - PS4, PS5",
            image: "https://source.unsplash.com/random",
            currency: "GHS",
            price: "70.99",
            discount: 0,
            tags: ["Action", "PS4"],
            description: "Cyberpunk 2077 is an open-world, action-adventure story set in Night City, a megalopolis obsessed with power, glamour and body modification. You play as V, a mercenary outlaw going after a one-of-a-kind implant that is the key to immortality.",
        },
        {
            id: 6,
            name: "Call Of Duty: Black Ops Cold War",
            image: "https://source.unsplash.com/random",
            currency: "GHS",
            price: "10.99",
            discount: 0,
            tags: ["Action", "PS5"],
            description: "Cyberpunk 2077 is an open-world, action-adventure story set in Night City, a megalopolis obsessed with power, glamour and body modification. You play as V, a mercenary outlaw going after a one-of-a-kind implant that is the key to immortality.",
        },
        {
            id: 7,
            name: "NBA 2K21 Mamba Forever - PlayStation 4",
            image: "https://source.unsplash.com/random",
            currency: "GHS",
            price: "30.99",
            discount: 0,
            tags: ["Action", "PS4"],
            description: "Cyberpunk 2077 is an open-world, action-adventure story set in Night City, a megalopolis obsessed with power, glamour and body modification. You play as V, a mercenary outlaw going after a one-of-a-kind implant that is the key to immortality.",
        },
        {
            id: 8,
            name: "Assasins Creed Valhalla",
            image: "https://source.unsplash.com/random",
            currency: "GHS",
            price: "30.99",
            discount: 0,
            tags: ["Action", "PS4"],
            description: "Cyberpunk 2077 is an open-world, action-adventure story set in Night City, a megalopolis obsessed with power, glamour and body modification. You play as V, a mercenary outlaw going after a one-of-a-kind implant that is the key to immortality.",
        },
    ],
    [
        {
            id: 9,
            name: "Cyberpunk 2077 Standard Edition - PS4, PS5",
            image: "https://source.unsplash.com/random",
            currency: "GHS",
            price: "30.99",
            discount: 0,
            tags: ["Action", "PS4"],
            description: "Cyberpunk 2077 is an open-world, action-adventure story set in Night City, a megalopolis obsessed with power, glamour and body modification. You play as V, a mercenary outlaw going after a one-of-a-kind implant that is the key to immortality.",
        },
        {
            id: 10,
            name: "Call Of Duty: Black Ops Cold War",
            image: "https://source.unsplash.com/random",
            currency: "GHS",
            price: "30.99",
            discount: 0,
            tags: ["Action", "PS5"],
            description: "Cyberpunk 2077 is an open-world, action-adventure story set in Night City, a megalopolis obsessed with power, glamour and body modification. You play as V, a mercenary outlaw going after a one-of-a-kind implant that is the key to immortality.",
        },
        {
            id: 11,
            name: "NBA 2K21 Mamba Forever - PlayStation 4",
            image: "https://source.unsplash.com/random",
            currency: "GHS",
            price: "30.99",
            discount: 0,
            tags: ["Action", "PS4"],
            description: "Cyberpunk 2077 is an open-world, action-adventure story set in Night City, a megalopolis obsessed with power, glamour and body modification. You play as V, a mercenary outlaw going after a one-of-a-kind implant that is the key to immortality.",
        },
        {
            id: 12,
            name: "Assasins Creed Valhalla",
            image: "https://source.unsplash.com/random",
            currency: "GHS",
            price: "30.99",
            discount: 0,
            tags: ["Action", "PS4"],
            description: "Cyberpunk 2077 is an open-world, action-adventure story set in Night City, a megalopolis obsessed with power, glamour and body modification. You play as V, a mercenary outlaw going after a one-of-a-kind implant that is the key to immortality.",
        },
        {
            id: 13,
            name: "Cyberpunk 2077 Standard Edition - PS4, PS5",
            image: "https://source.unsplash.com/random",
            currency: "GHS",
            price: "30.99",
            discount: 0,
            tags: ["Action", "PS4"],
            description: "Cyberpunk 2077 is an open-world, action-adventure story set in Night City, a megalopolis obsessed with power, glamour and body modification. You play as V, a mercenary outlaw going after a one-of-a-kind implant that is the key to immortality.",
        },
        {
            id: 14,
            name: "Call Of Duty: Black Ops Cold War",
            image: "https://source.unsplash.com/random",
            currency: "GHS",
            price: "30.99",
            discount: 0,
            tags: ["Action", "PS5"],
            description: "Cyberpunk 2077 is an open-world, action-adventure story set in Night City, a megalopolis obsessed with power, glamour and body modification. You play as V, a mercenary outlaw going after a one-of-a-kind implant that is the key to immortality.",
        },
        {
            id: 15,
            name: "NBA 2K21 Mamba Forever - PlayStation 4",
            image: "https://source.unsplash.com/random",
            currency: "GHS",
            price: "30.99",
            discount: 0,
            tags: ["Action", "PS4"],
            description: "Cyberpunk 2077 is an open-world, action-adventure story set in Night City, a megalopolis obsessed with power, glamour and body modification. You play as V, a mercenary outlaw going after a one-of-a-kind implant that is the key to immortality.",
        },
        {
            id: 16,
            name: "Assasins Creed Valhalla",
            image: "https://source.unsplash.com/random",
            currency: "GHS",
            price: "30.99",
            discount: 0,
            tags: ["Action", "PS4"],
            description: "Cyberpunk 2077 is an open-world, action-adventure story set in Night City, a megalopolis obsessed with power, glamour and body modification. You play as V, a mercenary outlaw going after a one-of-a-kind implant that is the key to immortality.",
        },
    ],
];
